/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AuthLayout } from '../auth-layout'
import { AuthBrand } from '../components/auth-brand'
import { AuthCard } from '../components/auth-card'
import { useAuthChrome } from '../lib/auth-chrome-context'
import { useAuthRedirect } from '../hooks/use-auth-redirect'
import { OtpForm } from './components/otp-form'

export function Otp() {
  return (
    <AuthLayout>
      <OtpContent />
    </AuthLayout>
  )
}

function OtpContent() {
  const { t } = useTranslation()
  const { setAction: setAuthChromeAction } = useAuthChrome()
  const { redirectToLogin } = useAuthRedirect()
  const [useBackupCode, setUseBackupCode] = useState(false)

  const goSignIn = useCallback(() => {
    redirectToLogin()
  }, [redirectToLogin])

  useEffect(() => {
    setAuthChromeAction({
      label: t('Log in'),
      onClick: goSignIn,
    })
    return () => setAuthChromeAction(null)
  }, [setAuthChromeAction, t, goSignIn])

  return (
    <AuthCard className='flex w-full max-w-[360px] flex-col items-center gap-6 text-center'>
      <div className='flex w-full flex-col items-center gap-4'>
        <AuthBrand />
        <div className='flex flex-col items-center gap-2'>
          <h1 className='text-lg font-semibold leading-7 tracking-[-0.09px]'>
            {useBackupCode
              ? t('Enter backup code')
              : t('Verify Google Authenticator')}
          </h1>
          <p className='text-muted-foreground text-xs leading-5'>
            {useBackupCode
              ? t('Enter one of your one-time backup codes')
              : t(
                  'Enter the 6-digit code generated by Google Authenticator App'
                )}
          </p>
        </div>
      </div>
      <OtpForm
        useBackupCode={useBackupCode}
        onToggleMode={() => setUseBackupCode((v) => !v)}
        className='w-full'
      />
    </AuthCard>
  )
}
